#!/bin/bash

if [[ ! -d "./bin/" ]]
then
    mkdir ./bin/
fi

if [[ $1 = "" ]]
then
    build="release"
else
    build=$1
fi

args_always="-DBUILD_LINUX \
src/linux_pd_path.c \
src/puddle_test.c \
src/string_view.c \
-Iinclude/ \
-Wextra -Wall -Wpedantic -Wconversion -Wshadow -Wsign-compare -Wtype-limits -Wunused \
-fuse-ld=mold"

args_release="-O2"

args_debug="-DDEBUG -g -O0"

args_asan="$args_debug -DASAN \
-fsanitize=address,leak,undefined \
-fno-omit-frame-pointer \
-static-libasan \
-O0"

function compile()
{
    echo "identifying a compiler..."

    clang --version > /dev/null
    if [[ $? = 0 ]]
    then
        echo "found clang."
        compiler="clang"
    else
        gcc --version > /dev/null
        if [[ $? = 0 ]]
        then
            compiler="gcc"
        else
            echo -e "\033[31m\nERROR: no suitable compiler found.\n\033[0m"
        fi
    fi

    echo ""
    echo -e "\033[36mcompiling puddle...\033[0m"
    echo ""

    if [[ ! -d ./bin/$build ]]
    then
        mkdir ./bin/$build
    fi

    echo "compiling $build build with the following command:"
    echo "$compiler $1"
    $compiler $1
    if [[ $? != 0 ]]
    then
        echo -e "\033[31m\nERROR: $compiler failed to compile puddle.\n\033[0m"
        exit -1
    fi
    mv ./a.out ./bin/$build/puddletest
}

if [[ $build = "release" ]]
then
    compile "$args_always $args_release"
else
if [[ $build = "debug" ]]
then
    compile "$args_always $args_debug"
else
if [[ $build = "asan" ]]
then
    compile "$args_always $args_asan"
else
    echo -e "\033[31m\nERROR: invalid make config: $build.\033[0m"
    exit 3;
fi
fi
fi

echo -e "\n"

if [[ $2 = "--compile-only" ]]
then
    exit 0
fi

chmod +x ./bin/$build/puddletest
./bin/$build/puddletest
