#!/bin/bash

if [[ ! -d "./obj/" ]]
then
    mkdir ./obj/
fi

if [[ ! -d "./build/" ]]
then
    mkdir ./build/
fi

if [[ ! -d "./bin/" ]]
then
    mkdir ./bin/
fi

if [[ $1 = "" ]]
then
    build="release"
else
    build=$1
fi

if [[ $build = "asan" ]] || [[ $build = "debug" ]] || [[ $build = "release" ]]
then

    echo ""
    echo -e "\033[36mcompiling puddle...\033[0m"
    echo ""
    premake5 gmake

    pushd ./build/ > /dev/null
    make config=$build\_linux
else
    echo -e "\033[31m\nERROR: invalid make config: $build.\033[0m"
    exit -2;
fi

if [[ $? != 0 ]]
then
    echo -e "\033[31m\nERROR: failed to compile puddle.\n\033[0m"
    exit -1
fi

echo -e "\n"

if [[ $2 = "--compile-only" ]]
then
    exit 0
fi

popd > /dev/null

echo -e "\033[36mrunning string_view unit tests...\033[0m\n"

chmod +x ./bin/$build/svtest
./bin/$build/svtest
